name: CI
on: pull_request

jobs:
  build:

    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
        node:
          - 14
    runs-on: ${{ matrix.os }}

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

      - name: Install dependencies for Example
        run: yarn
        working-directory: ./example

      - name: Run integration tests
        run: yarn test
        working-directory: ./example
